### ISSUE TITLE
[BUG] Every Time I relaunch the game the modules reset to default position

### ISSUE THREAD

**Issue by StonksSelected** [GoldpawsStuff/AzeriteUI5#1]
### Is this issue for AzeriteUI for Dragonflight?

- [x] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Title explains it enough

### To reproduce

For me just relaunch the game

### Expected behavior

Modules remained where they were placed in edit mode

### Additional context

I have deleted the party frame texture to get the original frames

**Comment by Goldpaw** [comment]
yeah, that was my fault. it should be fixed in the latest public builds on curseforge now.
