### ISSUE TITLE
[BUG] Dragon riding bar position is reset every time I switch between characters

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#10]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The dragon riding bar goes to the left of the screen every time I switch between characters.

### To reproduce

Switch between two characters who have access to dragon riding.

### Expected behavior

The position should be saved.

### Screenshots

![Screenshot 2023-01-09 105138](https://user-images.githubusercontent.com/120369133/211281878-02d1bb10-1c3f-4777-a9e9-096070dc0920.png)

### Additional context

Version 5.0.21-Beta

**Comment by Goldpaw** [comment]
Fixed!
