### ISSUE TITLE
[BUG] Switching Specs Resets Layout 

### ISSUE THREAD

**Issue by Scruffynerfherding** [GoldpawsStuff/AzeriteUI5#13]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every time I change specializations the entire AzeriteUI layout completely resets. Typing /resetlayout every time I switch specs is the only way to fix the issue. 

### To reproduce

Switch specializations on any character from your current spec to a different one. 

### Additional context

No additional context needed.

**Comment by deftanksfault** [comment]
Hey, I had the same issue at some point. Did you try to disable all add-ons other than AzeriteUI? It was due to a conflict with another add-on on my end, so I just removed it. Not great if you need it but at least that fixed the problem for me.

**Comment by Goldpaw** [comment]
No longer applies as 5.1 is out and the entire settings and profiling system has been changed.
