### ISSUE TITLE
[Feature] Spell ID 

### ISSUE THREAD

**Issue by ardacam** [GoldpawsStuff/AzeriteUI5#16]
### Is this feature request for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Adding **spell id** to tooltip will improve user experience while using weakauras or any related addon.

**Comment by Goldpaw** [comment]
Added in 5.0.41-RC
