### ISSUE TITLE
[BUG]  /reload Chat Command Forcibly Enables Vanilla UI Buff Icons

### ISSUE THREAD

**Issue by Scruffynerfherding** [GoldpawsStuff/AzeriteUI5#18]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Typing the /reload chat command enables the vanillaUI buff icons on the right side of the UI by the minimap. The only way to fix this is to completely log out and log back in. 

### To reproduce

type /reload 

### Screenshots

![WoWScrnShot_011623_190815](https://user-images.githubusercontent.com/48338420/212783133-97a48895-a38f-47ba-a33b-c1d0c8837aa6.jpg)

### Additional context

None

**Comment by Goldpaw** [comment]
Going to ask you to test this without addons. Because I have reloaded 7 times in a row, and this does not happen. 

So something else outside of AzeriteUI is forcefully re-enabling the buff frame for you.

**Comment by Scruffynerfherding** [comment]
> Going to ask you to test this without addons. Because I have reloaded 7 times in a row, and this does not happen.
> 
> So something else outside of AzeriteUI is forcefully re-enabling the buff frame for you.
> 
> Edit: Meaning this is most likely a compatibility problem with another addon trying to do some of the same things as AzeriteUI. I need more info to make a fix for it!

Understood, I'll log in shortly and start testing this for you. Thanks for the reply :)

**Comment by Scruffynerfherding** [comment]
Apologies for the delay. I've tested the mod like you suggested and after disabling all my mods, completely logging back out and back in again, the bug still remained. Below you'll see screenshots for further evidence, including a series of screens shots showcasing all the mods I have and that they were disabled. 
![WoWScrnShot_012123_131043](https://user-images.githubusercontent.com/48338420/213881045-21fa7b6d-0df4-4ec5-a7db-6ecac8f00f90.jpg)
![WoWScrnShot_012123_130645](https://user-images.githubusercontent.com/48338420/213881048-42f54e21-de69-43ee-b52a-353a6c96163f.jpg)
![WoWScrnShot_012123_130640](https://user-images.githubusercontent.com/48338420/213881050-34fc5b98-1b1f-42a1-9ce2-b21d07147cd3.jpg)
![WoWScrnShot_012123_130635](https://user-images.githubusercontent.com/48338420/213881054-7647e9be-90c3-4ef7-9ae4-c1636fa0be99.jpg)

**Comment by Goldpaw** [comment]
Guess I must've forgotten to close this. Fixed this several builds ago! It was a problem that started in 10.0.5, due to changes implemented by Blizzard!
