### ISSUE TITLE
[BUG] Unable to remove costumes and activated toys 

### ISSUE THREAD

**Issue by Scruffynerfherding** [GoldpawsStuff/AzeriteUI5#19]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This has been an issue since day one of Dragonflight. I was waiting for a fix but I haven't seen one yet, so I though I'd make you aware. You are unable to right click (or left click?) remove things like transmog costumes from toys while in AzeriteUI. 

### To reproduce

When you use a toy to transform your appearance it appears as a "buff" icon mixed in with your other buff icons above your character health bar in AzeriteUI. In the VanillaUI you are able to simple click the appropriate icon and the transformation from said toy will disappear along with the icon. The only fix for this I've found is to completely disable AzeriteUI, reload, remove the icon to transform back, reenable AzeriteUI, reload, then it's fixed. 

### Additional context

None

**Comment by ColdLogical** [comment]
There hasnt every been support for this from AzeruiteUI. You need to `/cancelaura <Name>` to get rid of it

**Comment by Scruffynerfherding** [comment]
> There hasnt every been support for this from AzeruiteUI. You need to `/cancelaura <Name>` to get rid of it

Thanks, I'll try that. I've played exclusively with AzeriteUI since it was first introduced in BFA and I was able to remove toy and customize effects, so it was a baseline feature at some point.

**Comment by ColdLogical** [comment]
Goldpaw mentioned it has to do with filtering the buffs. If they get filtered, then they aren't allowed to be cancelled to prevent abuse (addons that just put buff buttons at your cursor to have immediate cancels or something). Not sure when those changes were.

**Comment by Goldpaw** [comment]
In the latest builds, I have added a full buff display up in the top right corner of the screen. You can't see it if you have a target. But if you deselect your target, and hold ctrl+shift, it pops up. And THERE you can cancel buffs! 

So that's the fix. I haven't documented this anywhere, so I'm assuming there will be more reports about this until I do! My bad!
