### ISSUE TITLE
[Feature] Remove Border and Resize Action Bar Buttons

### ISSUE THREAD

**Issue by APegram** [GoldpawsStuff/AzeriteUI5#20]
### Is this feature request for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

 If you remove the border via the code base, it has way too much spacing. As a user that uses 4 full action bars, buttons take up too much space in the UI (or just feels a bit clunky)

### Describe the solution you'd like

Borders to be removeable / thinner? And buttons able to be tightened up.

**Comment by Goldpaw** [comment]
Just disable the azeriteui bars and use bartender + masque. Not much point in providing this much customization when excellent addons already exist for it, and this one is compatible with them!
