### ISSUE TITLE
[BUG] Rogue(only) Chat Message Bug

### ISSUE THREAD

**Issue by Duolik** [GoldpawsStuff/AzeriteUI5#23]
### Game Flavor

Wrath Classic

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Message: FontString:SetText(): Font not set
Time: Mon Apr 24 15:08:54 2023
Count: 1
Stack: FontString:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@Interface/AddOns/AzeriteUI/Components/Misc/ChatBubbles.lua"]:186: in function `?'
[string "@Interface/AddOns/AzeriteUI/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <.../AddOns/AzeriteUI/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "?"

### To reproduce

When I use Night Elf Rogue, a bug appears whenever I say anything.

### Additional context

-

**Comment by Goldpaw** [comment]
The whole chat bubble module in AzeriteUI has been removed due to its buggy nature. This no longer applies.
