### ISSUE TITLE
[Feature] Raid Frames

### ISSUE THREAD

**Issue by JulianChow94** [GoldpawsStuff/AzeriteUI5#25]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hello, I'm currently using AzeriteUI-5.0.62-RC for Dragonflight, and this is a feature issue but i'm unsure if its also a bug.

I'm really into the aesthetic and design of the UI suite but I've noticed that the default raid frames still show up. I've seen a youtube release video of AzeriteUI and it describes the raid frames feature which seems like its not there (or its bugged for me and it doesn't show up).

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/5642774/235525960-74fd680c-dfd8-4512-bc09-625730ca49b7.png)
The above raid frames from the following release video: https://www.youtube.com/watch?v=d004xzZvTHw

### Describe alternatives you've considered

I've tried disabling everything except AzeriteUI and it still doesn't show up so I don't think its a conflict with another addon

**Comment by Goldpaw** [comment]
Yeah, raid frames aren't done for AzeriteUI5 yet. They're coming in version 5.1, which I'm working on now. There'll also be a full graphical options menu in that version!

**Comment by Goldpaw** [comment]
Added in 5.1.

**Comment by JulianChow94** [comment]
Thanks!
