### ISSUE TITLE
[BUG] Changing global UI scale throws error and does not apply to frames

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#29]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing the global UI scale in graphics settings throws an error. Also, does not affect scale of Azerite frames.

### To reproduce

Moving UI scale slider and selecting apply.

### Expected behavior

Azerite frames should scale based on slider value.

### Additional context

Scaling worked in previous version.

Error log: [UI Scale.txt](https://github.com/GoldpawsStuff/AzeriteUI5/files/11777651/UI.Scale.txt)

**Comment by Billybishop** [comment]
This seems to potentially be related to a current bug that is preventing the UI element positions and scales from being saved as well - I believe this is a recent quirk due to the options/settings/profiles update that has been rolling out, I would expect it to be resolved after the options interface is complete

**Comment by Billybishop** [comment]
I've looked into this a little further and I believe the state of MoveableFrames and EditMode to be the cause. At least it's not clear to me that the layout positions and scales are actually being saved at the moment.

**Comment by Goldpaw** [comment]
Shouldn't be any scaling issues in 5.1, which changes the system completely. 

UI scaling through the game's graphic settings changes the game's own windows and elements. Any custom frames created by AzeriteUI will rescale themself to look the same when the user changes the game's UI scale. This is intended. The idea is to be able to adjust the size of the default game windows without interfering with our UI when doing it.

Anything created by AzeriteUI 5.1 can be scaled individually when using the `/lock` mode.
