### ISSUE TITLE
[BUG] Lua error when clicking on legacy raid boss unit frame

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#3]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had the following error when I clicked on the unit frame of any boss from legacy raids (here The Nighthold).
Reloading the UI didn't fix the issue.

### To reproduce

Enter The Nighthold raid and go to the first boss, then click on its unit frame.

### Screenshots

![Screenshot 2023-01-02 111342](https://user-images.githubusercontent.com/120369133/211142439-840cfb27-5614-463e-9c22-1f08ced235f3.png)

### Additional context

/

**Comment by Goldpaw** [comment]
Is that bugsack? Because it reports the completely wrong line number for the bug. Bugsack caches similar bugs up and messes up the line numbers. It makes the bug very hard to track. For a developer like me, bugsack is actually inferior to the default wow error window.

**Comment by deftanksfault** [comment]
I don't know bugsack, but I may have sent you the error I got with AzeriteUI 4, my bad. That would explain the wrong line number. I had the same error with AzeriteUI 5 though, do you want me to try to reproduce the error the next time I play and post a screenshot here? So you can get the correct line number.

**Comment by deftanksfault** [comment]
Seems fIxed with latest version (5.0.22-Beta)
