### ISSUE TITLE
[Feature] Raidframe layout options

### ISSUE THREAD

**Issue by Goldpaw** [GoldpawsStuff/AzeriteUI5#31]
### Game Flavor

Dragonflight, Wrath Classic, Classic Era

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Raidframes have a static layout for all raid sizes. This is not ideal. 

### Describe the solution you'd like

Add options for layout, growth, filtering and sorting.

**Comment by Combobulates** [comment]
Hi, me again. Again, if there is a better place to ask this please let me know.
When I have join a raid I have raid frames on my screen, I don't want them - I don't have raid frames enabled in edit mode
but the UI insists on adding them. Can I disable them from 'lock' mode?

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/117677754/3fa3edb8-b1b4-4e8b-9ba4-e4f756ec265f)

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/117677754/eb595bd0-915f-4777-99ba-45aedacdde7b)

**Comment by Goldpaw** [comment]
There were some issues with this, but it's fixed in the latest updates. The place to set raidframe visibilities are in the `/azerite` options menu under "raidframes". The options in edit mode has nothing to do with AzeriteUI visibility.
