### ISSUE TITLE
Import profile/universal profiles.

### ISSUE THREAD

**Issue by Combobulates** [GoldpawsStuff/AzeriteUI5#35]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm sure you can do this but I can't figure it out.

I have customised my UI for character A using /lock (edit mode)

I want to use it on all my characters...B,C,D

How do I select it/import it like you would normally use a addon profile.

Thanks.

### Describe the solution you'd like

Use a profile across characters, or Import option. Or tell me which file to edit.

### Describe alternatives you've considered

Doing it manually for 20 characters.

**Comment by Goldpaw** [comment]
Just open `/az` or `/lock` and select the profile you want. Profiles are shared by all characters, while profile choice is stored per character. 

The settings profiles aren't named after your characters, which might feel unusual, but they're still profiles. The default one is named `Azerite`, but you can create as many as you like and name them what you want. 

And remember to always update to the most recent versions of the UI.

**Comment by Combobulates** [comment]
I don't think a profile you make on one character is viewable/selectable at all by another character.
However you are correct that the default 'azerite' profile is shared/applied across characters.
I have made profiles on characters and no other characters can see that profile to choose it.
I can make all characters use 'azerite' though so that will work for me.

Thankyou again.
