### ISSUE TITLE
[Bug] Absorb overlays not showing on the player health bar

### ISSUE THREAD

**Issue by LitongQi** [GoldpawsStuff/AzeriteUI5#36]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

As a shadow priest, when i have the "void shield" talent, i found that the shield is not clearly shown on the top of the hp bar. I remember when i used to play mage, it do have a tranparent shield there.

### Describe the solution you'd like

just wanna see the shield value clearly.

### Describe alternatives you've considered

or maybe add one sub bar at the bottom of the hp bar to show what number of shield i have.

### Additional context

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/62735079/88f00aad-e051-49b4-96b6-8fae62f18878)
![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/62735079/30b13973-95ba-4653-808c-387a94e56364)

**Comment by Goldpaw** [comment]
But normal untalented Power Word: Shield does show up, right? Is the number in paranthesis the value left on the shield? 

I'm guessing this is an issue with when the absorb bar is updated, because it should've been there. It's text value is, so clearly the unitframe gets what's happening. 

Looking into it!

**Comment by Goldpaw** [comment]
Nevermind, there's a bug preventing any absorb bars from showing up, it appears! At least on the playerframe. Fix coming!

**Comment by Goldpaw** [comment]
Fixed in 5.2.77-Alpha.
