### ISSUE TITLE
[BUG] Mana ball not displaying on player frame

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#39]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The mana ball is not displaying on the player frame. This is only occurring on my level 70 character. All other lower level characters are not affected. Class isn't a factor (I have noticed some use the azerite shard instead of the ball). I also get an LUA error.

I have tried fixing the problem using the following methods without success:

Reloading UI.
Resetting settings.
Installing from GitHub, Wago, and CurseForge.
Clearing WTF folder.
Clearing Cache folder.

See attached LUA error: [LUA error.txt](https://github.com/GoldpawsStuff/AzeriteUI5/files/12101395/LUA.error.txt)

### To reproduce

Have a max level character in Dragonflight.

### Expected behavior

Mana ball is visible.

### Screenshots

<img width="696" alt="Screenshot 2023-07-20 at 12 04 02 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/1bc46675-2504-4343-a633-b52b28b77630">

### Additional context

See screenshot.

**Comment by Goldpaw** [comment]
Fixed in 5.2.82-RC!
