### ISSUE TITLE
[BUG] Boss's health bar looks empty, no portrait

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#4]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In The Nighthold, Gul'dan's health bar is not colored and doesn't have a 3d portrait

### To reproduce

Enter The Nighthold and go to the last boss

### Screenshots

![Screenshot 2023-01-02 114625](https://user-images.githubusercontent.com/120369133/211142702-48e76b4d-2021-439c-89b9-6179aa2a02bf.png)

### Additional context

-

**Comment by Goldpaw** [comment]
Almost certain this is a result of the target frame bugging out first from the bug in your other report, #3. The first bug halts the updates, and then we get this.

**Comment by deftanksfault** [comment]
Fixed with latest version (5.0.22-Beta)
