### ISSUE TITLE
team unitframe issue

### ISSUE THREAD

**Issue by Dcryfm** [GoldpawsStuff/AzeriteUI5#42]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The team unitframe of 5 people is still visible even when it is not enabled

### To reproduce

/Azerite
Do not enable the 5-person team unitframe

### Additional context

This issue occurs in 5.2.111-RC

**Comment by Goldpaw** [comment]
I think I've found the bug. It fails to load visibility conditions when it is disabled, which leaves it fully visible. Oops. Fix coming in the next update!

**Comment by Goldpaw** [comment]
Fixed.
