### ISSUE TITLE
[Feature] Azerite nameplates on player characters

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#44]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

At the moment the Azerite nameplates only appear on current faction players in the open world.

They do not appear on opposite faction players or on current faction players while in dungeons or raids.

### Describe the solution you'd like

Add Azerite nameplates for all player characters in open world or instanced content.

### Additional context

NPC nameplates seem to work most of the time.

There are some dungeon and raid bosses where the Azerite nameplates do not appear.

**Comment by Goldpaw** [comment]
No addon can replace or modify friendly nameplates in dungeons or raids, this is a blizzard limitation and has existed for years. 

Also, not all units have nameplates all the time. Some bosses needs to become interactable before their plate appears. No bugs here, just intended blizzard behavior.
