### ISSUE TITLE
[Feature] Hide Nameplates along with rest of UI for even more Immersion

### ISSUE THREAD

**Issue by AdvLeon** [GoldpawsStuff/AzeriteUI5#47]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First of all I just want to say thank you for extending compatibility with Immersion and allowing Unit Frames to be hidden. I have however noticed that Nameplate health bars are still visible.

### To reproduce

Immersion add-on loaded - enabled fade UI when in dialogue.
Enabled nameplates in AzeriteUI.
Tested by disabling all add-ons except AzeriteUI and Immersion.

### Expected behavior

Nameplate should be hidden.

### Screenshots

![downloadfile(1)~2](https://github.com/GoldpawsStuff/AzeriteUI5/assets/42209668/9508a488-3817-4c61-89fc-6363072e6047)

### Additional context

Confirmed using latest version.

**Comment by Goldpaw** [comment]
Nameplates aren't parented to the UIParent frame which the rest of the UI lives in, it is parented to the WorldFrame. And thus wouldn't be hidden by Immersion, as that only modifies the opacity of the UIParent frame. 

Are you sure Immersion hides the default blizzard plates?

**Comment by Goldpaw** [comment]
I tried with nothing but the default Blizzard UI and Immersion enabled. Nameplates still show when the rest is faded out. 

So this is not a bug, and since we can't change what frame the nameplates are parented to (blizzard restriction), this isn't a feature I wish to implement either. 

![Screenshot from 2023-10-26 13-39-29](https://github.com/GoldpawsStuff/AzeriteUI5/assets/6476535/0a02d56c-458c-4703-9bad-6aaf81b10cb1)

![Screenshot from 2023-10-26 13-39-31](https://github.com/GoldpawsStuff/AzeriteUI5/assets/6476535/9cf8a351-3a99-4f34-8a6b-ae0191dfbacb)

**Comment by AdvLeon** [comment]
> I tried with nothing but the default Blizzard UI and Immersion enabled. Nameplates still show when the rest is faded out.
> 
> So this is not a bug, and since we can't change what frame the nameplates are parented to (blizzard restriction), this isn't a feature I wish to implement either.
> 
> ![Screenshot from 2023-10-26 13-39-29](https://user-images.githubusercontent.com/6476535/278370544-0a02d56c-458c-4703-9bad-6aaf81b10cb1.png)
> 
> ![Screenshot from 2023-10-26 13-39-31](https://user-images.githubusercontent.com/6476535/278370531-9cf8a351-3a99-4f34-8a6b-ae0191dfbacb.png)

Fair enough. Thanks for looking into it 😃

**Comment by Goldpaw** [comment]
Having that said, I'm not opposed to the feature. Might be some hackish ways I can make my nameplates piggyback on the UIParent's opacity changes without actually messing with their own opacity, weird as that might sound. 

You know what, I'm re-opening this as a feature request and giving it a try! Worst thing that can happen is that I don't get it working, and we're there already! :D

**Comment by Goldpaw** [comment]
hah! 
Nameplates fading when Immersion says so fram the next update! :D

![Screenshot from 2023-10-27 15-25-38](https://github.com/GoldpawsStuff/AzeriteUI5/assets/6476535/72c42984-be91-40bb-9580-f286702a2e59)

![Screenshot from 2023-10-27 15-25-43](https://github.com/GoldpawsStuff/AzeriteUI5/assets/6476535/f478ec25-486a-4980-b755-2a00fad80927)

**Comment by AdvLeon** [comment]
Whoa that's amazing! Thank you so much for your persistence! 🙏🤩

**Comment by Goldpaw** [comment]
Added in 5.2.119-RC.
