### ISSUE TITLE
[Feature] Disable Objectives Tracker styling

### ISSUE THREAD

**Issue by AdvLeon** [GoldpawsStuff/AzeriteUI5#48]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I love the look of the UI but it would be nice to have the option to toggle the Objective/Quests Tracker and revert to the default blizzard appearance for those that prefer how that looks.

### Describe the solution you'd like

A toggle option in the /azerite menu.

### Describe alternatives you've considered

Seems to be possible by messing with the add-on files but an official solution seems cleaner :)

### Additional context

No big deal if it isn't possible, it's a very minor thing. I appreciate all your hard work! 🙂

**Comment by anaarkei** [comment]
The tracker already has a toggle.

Per the [changelog](https://github.com/GoldpawsStuff/AzeriteUI5/blob/main/CHANGELOG.md#52116-rc-2023-10-21), this is experimental.

<img width="912" alt="Screenshot 2023-10-24 at 5 19 22 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/2d683d59-138b-4122-a53c-7cf5b664f91b">

**Comment by AdvLeon** [comment]
> The tracker already has a toggle.
> 
> Per the [changelog](https://github.com/GoldpawsStuff/AzeriteUI5/blob/main/CHANGELOG.md#52116-rc-2023-10-21), this is experimental.
> <img alt="Screenshot 2023-10-24 at 5 19 22 pm" width="912" src="https://user-images.githubusercontent.com/27684333/277578540-2d683d59-138b-4122-a53c-7cf5b664f91b.png">

I did see that but all it seems to do is completely disable the quest tracker, including the Blizzard version.

**Comment by Goldpaw** [comment]
On the topic of experimental features, try these: 

`/run ObjectiveTrackerFrame:SetTheme("blizzard")`
`/run ObjectiveTrackerFrame:SetTheme("azerite")`

😎

**Comment by Goldpaw** [comment]
And yes, that is saved through sessions.

**Comment by AdvLeon** [comment]
> On the topic of experimental features, try these:
> 
> `/run ObjectiveTrackerFrame:SetTheme("blizzard")` `/run ObjectiveTrackerFrame:SetTheme("azerite")`
> 
> 😎

I just tested and it works perfectly! Goldpaw you are a legend! 🤩

**Comment by Goldpaw** [comment]
The reason I haven't put this into the menu yet is because when I wrote this it was sort of buggy. And I didn't want to put a bunch of buggy features into the public version. 

But I might as well do it, add it to the options menu I mean. I can always just add a warning that theming is an experimental feature which might produce bugs and the solution is to stick to the azerite theme in that case. 👍🏻

**Comment by Goldpaw** [comment]
Added as an actual `/azerite` menu option in 5.2.119-RC.
