### ISSUE TITLE
[Feature] Red colored debuffs border

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#5]
### Is this feature request for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, the buffs have a dark gray border (which looks great ❤️) but the debuffs share the same color, making them hard to tell apart at first glance. It would be nice to have a red border for the debuffs, as seen in this screenshot of a previous version of the interface:

![sj1rcf5j7v421](https://user-images.githubusercontent.com/120369133/211143565-ce941a36-8aca-45f0-998a-36b7a19978f7.png)

### Describe the solution you'd like

A dark gray border for the buffs and a red border for the debuffs

**Comment by Goldpaw** [comment]
Debuffs should be debuff colored. I just implemented that for the player frame, guess I forgot to also update that for the target frame.  Will get it done!

**Comment by deftanksfault** [comment]
Sorry, there might be a misunderstanding. The screenshot I posted is from a previous version of the UI, but I noticed that after leaving a BG, the "deserter" debuff was not red on my player frame, but dark gray like the buffs.

**Comment by Goldpaw** [comment]
Forgot to close this, but I fixed the debuff border coloring a while back. They now has the color of the magic school or red if it's just a general debuff.
