### ISSUE TITLE
[BUG] Expandable abilities vanish if using fading action bars

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#50]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Selecting an expandable ability (e.g. Portal or Teleport) when fading action bars is enabled and moving the cursor over the buttons for the different portal/teleport locations causes the buttons to disappear, however are still selectable and can be distinguished using the tooltip.

Additionally, buttons for portal/teleport locations are displaying the default UI and not using Azerite UI.

### To reproduce

Use Portal or Teleport with fading action bars enabled.

### Expected behavior

Should be able to see what one is selecting.

### Screenshots

Button selected:

<img width="562" alt="Screenshot 2023-11-18 at 11 50 26 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/a0f11e84-1af0-4509-a64b-22b8a6f30fdf">

---
Cursor moved off button and hovering over teleport location:

<img width="551" alt="Screenshot 2023-11-18 at 11 50 36 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/22185434-bc0d-4d6f-b273-971da0eafbd1">

### Additional context

Disabling fading action bars resolves the issue.

**Comment by Goldpaw** [comment]
Absolutely. I'll see if I can get the pull-out bars to ignore the opacity of the other buttons. Fix coming!

**Comment by Goldpaw** [comment]
Fixed in 5.2.129-RC
