### ISSUE TITLE
[BUG] [Classic] "Usage: HookScript(object, method, [handler]): You can only hook a script on a frame object"

### ISSUE THREAD

**Issue by juanfm288** [GoldpawsStuff/AzeriteUI5#52]
### Game Flavor

Classic Era

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Only the main bar is displayed even if you have all the actionbars enabled on the AzeriteUI
When you open /lock the other bars appear as an Plus

//////////////////////////// Lua Error
Message: ...eUI/Libs/LibFadingFrames-1.0/LibFadingFrames-1.0.lua:189: Usage: HookScript(object, method, [handler]): You can only hook a script on a frame object
Time: Mon Nov 20 16:18:43 2023
Count: 1
Stack: ...eUI/Libs/LibFadingFrames-1.0/LibFadingFrames-1.0.lua:189: Usage: HookScript(object, method, [handler]): You can only hook a script on a frame object
[string "=[C]"]: ?
[string "@Interface/AddOns/AzeriteUI/Libs/AceHook-3.0/AceHook-3.0.lua"]:143: in function <...ce/AddOns/AzeriteUI/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/AzeriteUI/Libs/AceHook-3.0/AceHook-3.0.lua"]:366: in function `HookScript'
[string "@Interface/AddOns/AzeriteUI/Libs/LibFadingFrames-1.0/LibFadingFrames-1.0.lua"]:189: in function `RegisterFrameForFading'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Prototypes/ActionBar.lua"]:288: in function `UpdateFading'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Prototypes/ActionBar.lua"]:271: in function `Update'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Prototypes/ActionBar.lua"]:254: in function `Enable'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Elements/ActionBars.lua"]:658: in function `UpdateEnabled'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Elements/ActionBars.lua"]:696: in function `UpdateSettings'
[string "@Interface/AddOns/AzeriteUI/Components/ActionBars/Elements/ActionBars.lua"]:783: in function <...riteUI/Components/ActionBars/Elements/ActionBars.lua:762>
[string "=[C]"]: ?
[string "@Interface/AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/AzeriteUI/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = "Usage: HookScript(object, method, [handler]): You can only hook a script on a frame object"

### To reproduce

Using:
Wow Classic Version 1.15.0.52215
AzeriteUI Version: 5.2.130

### Expected behavior

The extra bars appear and can be used

### Screenshots

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/28316269/e8e42291-ea35-46da-9812-986206e83fe0)
![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/28316269/da1a81dc-b329-4c19-b447-025a94e67baa)
![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/28316269/169f76fa-101a-44c0-a1ed-486dea1bdbdc)

### Additional context

The issue does not happen for me on version  5.2.128

**Comment by Goldpaw** [comment]
Fixed in 5.2.131-RC
