### ISSUE TITLE
[Feature] Make Explorer Mode respect action bar fade setting for fully faded bars set to fade separately

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#54]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Occurs if Explorer Mode is enabled and all fades are selected, and ”Don’t fade in other action bars” is selected on an action bar.

Hovering the mouse over faded action bar (in this case, Action Bar 3) to make it display causes other action bars to appear (in this case, Action Bar 1 and the attached Player UnitFrame).

### To reproduce

Enable Explorer Mode with all fades selected

Select ”Don’t fade in other action bars” on an action bar other than Action Bar 1 or 2.

### Expected behavior

Action Bar 3 should be the only thing that appears on mouseover.

### Screenshots

<img width="1728" alt="Screenshot 2023-12-11 at 9 55 26 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/0a9203c8-0517-4ab2-8f4d-08f4e18219db">
<img width="1728" alt="Screenshot 2023-12-11 at 9 55 14 pm" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/27684333/8cf13d46-06c5-4ff1-8aa6-4071a3fc698b">

### Additional context

None

**Comment by Goldpaw** [comment]
Fix/implemented in 5.2.140-RC. Working as we want now!
