### ISSUE TITLE
[BUG] <title>bug for Rogue use  TricksoftheTrade  Spell(57934) in team

### ISSUE THREAD

**Issue by mizone** [GoldpawsStuff/AzeriteUI5#56]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when in team, using  TricksoftheTrade   , it will report a bug @AzeriteUI\Components\UnitFrames\Auras line 94

### To reproduce

when in team, Rogue using  TricksoftheTrade   , it will report a bug @AzeriteUI\Components\UnitFrames\Auras line 94

### Additional context

when in team, Rogue using  TricksoftheTrade   , it will report a bug @AzeriteUI\Components\UnitFrames\Auras line 94

**Comment by Goldpaw** [comment]
That's not the error message. There is no file with that name in the UI, that path is to a folder. I need to see the actual error message. Screenshots are fine.

**Comment by mizone** [comment]
Message: ...ns/AzeriteUI/Components/UnitFrames/Auras/Filters.lua:94: attempt to compare nil with number
Time: Wed Dec 13 23:10:19 2023
Count: 2
Stack: ...ns/AzeriteUI/Components/UnitFrames/Auras/Filters.lua:94: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface/AddOns/AzeriteUI/Components/UnitFrames/Auras/Filters.lua"]:94: in function <...ns/AzeriteUI/Components/UnitFrames/Auras/Filters.lua:74>
[string "@Interface/AddOns/AzeriteUI/Libs/oUF/elements/auras.lua"]:367: in function <...terface/AddOns/AzeriteUI/Libs/oUF/elements/auras.lua:289>
[string "=(tail call)"]: ?

Locals: (*temporary) = <function> defined =[C]:-1



when i use 5.2.136, it is OK.  from 5.2.137,  this issue happens when do M+.

**Comment by mizone** [comment]
since you do below changes. 
<img width="1280" alt="1" src="https://github.com/GoldpawsStuff/AzeriteUI5/assets/13501972/3b4ada36-17db-42e6-b0e6-ff5627c17444">

**Comment by Goldpaw** [comment]
Should've been `button.timeLeft` not `data.timeLeft`. Fix coming shortly.

**Comment by Goldpaw** [comment]
Fixed in 5.2.145-RC.
