### ISSUE TITLE
[Feature] Allow hiding of Class Power in Explorer Mode

### ISSUE THREAD

**Issue by Scantraxx01** [GoldpawsStuff/AzeriteUI5#57]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using explorer mode the class power module stays visible.

### To reproduce

Enable Explorer Mode

### Additional context

none

**Comment by Goldpaw** [comment]
Well not a bug, because there is no option to hide it either. The classpower is an element of its own, not part of the player unitframe! 

But I'll add the option and change this to a feature request! :)

**Comment by Goldpaw** [comment]
Added in 5.2.147-RC

**Comment by Scantraxx01** [comment]
Cool, thank you!
