### ISSUE TITLE
[Feature] Hide keybind from actionbars

### ISSUE THREAD

**Issue by Scantraxx01** [GoldpawsStuff/AzeriteUI5#58]
### Game Flavor

Dragonflight

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

An option to disable the keybind overlay on the action bar icons would be great.

### Describe the solution you'd like

An option to enable or disable showing the key shortcut for each actionbar button.

**Comment by Goldpaw** [comment]
Added to `/azerite` on the main page of the actionbars menu in 5.2.148-RC.
