### ISSUE TITLE
[BUG][Solved] Cast bar disappearing every reload

### ISSUE THREAD

**Issue by DrFontanez** [GoldpawsStuff/AzeriteUI5#59]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cast bar is disappeared each time I opened the game or reloading addons. The cast bar on the health bar is fine.

I can disable and re-enable cast bar to make it show up for a while, but disappeared again after `/reload`.

### To reproduce

When you opened the game OR reloaded addons with `/reload`.

### Additional context

Version: `v5.2.151`

**Comment by Goldpaw** [comment]
Are you showing the "personal resource display", the nameplate for the player? Because the UI is set to hide the azeriteui castbar if the nameplate (which also has a castbar) is visible.

**Comment by DrFontanez** [comment]
Oh, yes I actually did that with "personal resource display" enabled, It seems we can get cast bar back with disabling it. Thanks for the troubleshooting!
