### ISSUE TITLE
[BUG] Quest Log on HUD disappearing 

### ISSUE THREAD

**Issue by Scruffynerfherding** [GoldpawsStuff/AzeriteUI5#6]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure if this is a bug with AzeriteUI or one of my other mods but the Quest Log that displays on the right of my screen on the HUD (not the actual quest journal itself) disappears every time I open a new window (like a trader, auction house, etc.) or just randomly. The only fix is to /reload.  I do have other UI mods installed and those are Bartender and Masque Azerite. 

### To reproduce

Click the arrow next to your tracked quests displayed on your HUD to hide the list of tracked quests. Then, open an auction house window, profession window, or any other window, and the the quest list on the HUD will disappear. Instead of hiding the quests and it removes the quest log entirely making it impossible to click the arrow to show the quests again. 

### Screenshots

![WoWScrnShot_010823_001707](https://user-images.githubusercontent.com/48338420/211181713-ffd960fe-3d75-424f-b9fe-3fbf66b3e01f.jpg)
![WoWScrnShot_010823_001723](https://user-images.githubusercontent.com/48338420/211181717-c48dc8f8-6fba-4890-aed6-707b8f0087c4.jpg)
![WoWScrnShot_010823_001736](https://user-images.githubusercontent.com/48338420/211181720-dedd190a-70f4-47e7-8543-23bc5fe22bf1.jpg)

### Additional context

None

**Comment by Goldpaw** [comment]
AzeriteUI does not hide or show the questlog. The EditMode in 10.0.5 made that impossible. This issue originated elsewhere.
