### ISSUE TITLE
[Feature] <Raid5 Frames usable in Raid10 and in Party Mode>

### ISSUE THREAD

**Issue by NuptupTDOW** [GoldpawsStuff/AzeriteUI5#61]
### Game Flavor

Wrath Classic, Classic Era

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I use Azerite UI in combination with Console port to have what I would consider the most enjoyable relaxed gaming UI for me personally, and I thoroughly love the combination, but I was recently introduced to one feature in the UI that I absolutely LOVE, but can't actually USE it for anything, and I'm unsure why it even exists, but I want more of it.

Currently, in Classic Era (and I assume Wrath), there are 4 different group frame types. There is Party (up to 5 players in a non-raid), Raid5 (up to 5 players in a raid), Raid25 (from 6-25 players in a raid), and Raid40 (26-40 players in a raid).

I have been using azerite for a long time now, and my only real complain as a group/raid leader was the inability to monitor mana bars and notable debuffs when in a dungeon or raid. In Party format, it shows a portrait, a health total OR percent, and it seems to sometimes show mana, but i haven't figured out when or why. Then I would convert a party directly into a Raid25 when I invite the 6th member and it shows only the name and hp. Raid 40 is understandably similar. 

However recently, I went ahead and converted a 3-player party into a raid because we were waiting for guildies, and I saw for the first time, the Raid5 format. And.., it's everything I want. A nice clean looking portrait, with a full mana bar display, and noteworthy buffs/debuffs. It's genuinely perfect for what I want. I would gladly replace the Party format AND the Raid 10 format with just, the Raid5, and extend it to be 10 players tall in 10-man raids. 

### Describe the solution you'd like

I would greatly appreciate the option in the settings to choose to replace the Party frames with the Raid 5 Frames, and also a similar option to create a Raid 10 format that uses the Raid 5 frames, with the option of 1x10 tall layout, or 2x5 layout. I personally would use the 1x10, but i know many would use 2x5 instead, and i think the option for both is important. 

### Describe alternatives you've considered

I have gone into the mod files myself and attempted to enable it, but my limited knowledge of wow's addon intricacies limited my attempts. I managed to make the game recognize the difference between a 10-man and 25 man group, instead of 5 and 25, but i couldn't get the 6th player's frame to appear. 

### Additional context

If you would like to discuss this more directly, you can add me on Discord at NuptupTDOW. I am very, very interested in this, and would even consider commissioning this functionality from you to add it to the mod.

**Comment by Goldpaw** [comment]
I'm going to be adding the mana/power bars to ALL group frames by default in the next update. So that part is coming. 

And I agree, we should have options to choose which kind of frames to use, and if the screen has room for 10 of these frames, then people should be able to choose that. 

You can sort of get them in parties already. If you disable the party frame module from the /azerite menu, the next sized group frame will be used instead, which would be the 5p raid frames frames. 

In theory, at least. I haven't actually tried. I'll make sure to add options to customize it more, and leave this issue open and post progress on that here! 👍🏻

**Comment by NuptupTDOW** [comment]
Awesome to hear, thank you very much! Is there currently a way to trick it to still use the 5-player raid when in a 10-player raid instead of the 25-player format? I mainly just like the 5-player raid frames because I like layout of the frames, the fact they show mana, and I like the portrait being there. The party frames being disabled fixes my party dungeon loadout, but if there's a quick and dirty fix I can make in the LUA files myself to have it work in 10 man raids, and only swap to the 25 man raid frames when an 11th member is added, that'd be absolutely ideal! :D

**Comment by NuptupTDOW** [comment]
I don't remember everything I tried last night, but I remember I specifically changed the detection to swap from Raid5 to Raid 25 to search for Raid11 exists instead of Raid6 exists, and when I had more than 5 people in the raid, but less than 11, it stayed using the Raid5 frames instead of swapping to the Raid25, which is good, but it didn't show the 6th character. I tried changing the layout options towards the top of the LUA file to allow Raid5 to have 10 units per column, and I also tried just adding a second column, but neither option would show the 6th character in the raid. I assume I'm just missing like.., one line of code that enables more than 5 people to be displayed, but I couldn't find it anywhere.

**Comment by NuptupTDOW** [comment]
I have some time to dig through the LUA files at work, and here's what I am going to be trying when I get home later tonight. Maybe you'll be able to tell if this should work or not seeing as you're more familiar with the code of course.

https://github.com/GoldpawsStuff/AzeriteUI5/commit/39a9718d710e5e0fcc1b96dbe6c3d6ac58a83c18

I'm not suggesting you personally use this code for your mod as I'm sure you'll have a more elegant method of doing it, but I just wanted to see if I could figure out how to make a quick and rough fix for myself in the meantime.

**Comment by Goldpaw** [comment]
There should be options in the `/azerite` menu to choose specifically what group frames to have visible in what group sizes now. So I'm closing this. 

It's a feature in progress, btw, and there will be more options and factors deciding the usage in the future than just group sizes.
