### ISSUE TITLE
[Feature] <Any plans for an Azerite themed chatlog?>

### ISSUE THREAD

**Issue by NuptupTDOW** [GoldpawsStuff/AzeriteUI5#63]
### Game Flavor

Dragonflight, Wrath Classic, Classic Era

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Not exactly a problem, but just wanted to ask if there's plans to make a chatlog window frame that is themed to match the Azerite aesthetic? I personally am a really big fan of the Azerite Themed tooltip window and would love to have a similar look for the chatlog. I am a freak who constantly has their chatlog on display and disables fade-out, because I'm constantly scrolling through chats and talking with people or forming groups or tracking things in combat, so my chat log is always there, it'd just be nice if it could also share the same look and feel as the rest of my ui. 

### Describe the solution you'd like

Make a frame for the chatlog to look similar to the tooltip box I guess?

### Additional context

I often slam my chatlog in the bottom left corner of my screen, and I am sometimes annoyed by the fact there's a gap underneath it to make room for the input bar, and I know there are mods to move the input bar above or whatever, but ideally if you're making a frame for the chatlog anyway, having a visual, built in, un-hide-able input box below the chatlog would be great. I think it could look really awesome!

**Comment by Goldpaw** [comment]
Don't really have any plans for this. I'm using my own addon BigInputBox to write with.
