### ISSUE TITLE
[BUG] Action Bar errors on new Classic update

### ISSUE THREAD

**Issue by mamasita666** [GoldpawsStuff/AzeriteUI5#66]
### Game Flavor

Classic Era

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Good day, on new update of classic wow SOD, version 1.15.1.53247 appears errors about action bar, pls help - cant live without this addon :)

### To reproduce

world load

### Additional context

Message: ...bs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua:2505: attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)
Time: Wed Feb  7 15:48:19 2024
Count: 16
Stack: ...bs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua:2505: attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)
[string "@Interface/AddOns/AzeriteUI/Libs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua"]:2505: in function `GetPassiveCooldownSpellID'
[string "@Interface/AddOns/AzeriteUI/Libs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua"]:2073: in function <...bs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua:2067>
[string "@Interface/AddOns/AzeriteUI/Libs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua"]:1482: in function <...bs/LibActionButton-1.0-GE/LibActionButton-1.0-GE.lua:1408>

Locals: self = AzeriteActionBar1Button1 {
 0 = <userdata>
 HotKey = AzeriteActionBar1Button1HotKey {
 }
 HighlightTexture = Texture {
 }
 NewActionTexture = Texture {
 }
 NormalTexture = AzeriteActionBar1Button1NormalTexture {
 }
 action = 0
 Border = AzeriteActionBar1Button1Border {
 }
 Flash = AzeriteActionBar1Button1Flash {
 }
 CheckedTexture = Texture {
 }
 Count = AzeriteActionBar1Button1Count {
 }
 Name = AzeriteActionBar1Button1Name {
 }
 FlyoutBorderShadow = AzeriteActionBar1Button1FlyoutBorderShadow {
 }
 _state_action = 1
 icon = AzeriteActionBar1Button1Icon {
 }
 state_actions = <table> {
 }
 AutoCastable = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 AutoCastShine = AzeriteActionBar1Button1Shine {
 }
 header = AzeriteActionBar1 {
 }
 id = 1
 PushedTexture = Texture {
 }
 SpellHighlightTexture = Texture {
 }
 __LAB_Version = 125
 outOfRange = false
 config = <table> {
 }
 FlyoutBorder = AzeriteActionBar1Button1FlyoutBorder {
 }
 _state_type = "action"
 state_types = <table> {
 }
 FlyoutArrow = AzeriteActionBar1Button1FlyoutArrow {
 }
 cooldown = AzeriteActionBar1Button1Cooldown {
 }
 zoneAbilityDisabled = false
}
_actionType = "spell"
actionID = 6603
onEquipPassiveSpellID = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)"

**Comment by Goldpaw** [comment]
Fixed
