### ISSUE TITLE
[BUG] Party Frame first member section is invisible

### ISSUE THREAD

**Issue by DrFontanez** [GoldpawsStuff/AzeriteUI5#69]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Party Frame first member section is invisible, But it is clickable.

### To reproduce

To present that the first member section is invisible, I toggle Show player to do that
![WoWScrnShot_022824_011802](https://github.com/GoldpawsStuff/AzeriteUI5/assets/91207879/f544a44f-62ac-4a1e-b4c3-b40b355d9b83)
![WoWScrnShot_022824_011805](https://github.com/GoldpawsStuff/AzeriteUI5/assets/91207879/8d956130-9a8c-47e9-aa91-41d5e56e2fa8)

### Additional context

It happened since 10.2.5 update, but somehow I have them back for a moment. After that it happened again and no matter which version it will be like this.

**Comment by Goldpaw** [comment]
fixed
