### ISSUE TITLE
[BUG] Eye icon not styled with AzeriteUI artwork

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#7]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The eye icon displayed when looking for a group is not styled using AzeriteUI artwork.

### To reproduce

Simply use the group finder

### Expected behavior

The eye icon should be styled with AzeriteUI artwork.

### Screenshots

![Screenshot 2023-01-08 110529](https://user-images.githubusercontent.com/120369133/211191120-df84e6dd-db6e-4313-bd80-d107ced3c609.png)

### Additional context

Version 5.0.21

**Comment by Goldpaw** [comment]
added and fixed for all three current wow flavors!
