### ISSUE TITLE
[BUG] Explorer mode doesnt work?

### ISSUE THREAD

**Issue by ulvfdfgtmk** [GoldpawsStuff/AzeriteUI5#71]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Explorer mode either doesnt fade out anything at all or doesnt fade stuff in when conditions are met.
Disabling explorer mode shows the UI as expected.

### To reproduce

-Fresh install of the addon
-Activate explorer mode
-Set option "After logging into the game" to 0
-Enter combat, UI doesnt get reactivated

### Additional context

I have only this addon running, tried fresh install, tried resetting options. Same behaviour everytime.

**Comment by Goldpaw** [comment]
Fixed.
