### ISSUE TITLE
[BUG] Every time I switch between characters, I have to re-enable secondary action bars

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#9]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have to type `/enablebar 2` every time I switch between my characters.

### To reproduce

Switch between two characters who have the action bar 2 enabled.

### Expected behavior

I should get my action bars back as I set them up when I log back into one of my characters.

### Additional context

Version 5.0.21-Beta

**Comment by Goldpaw** [comment]
Seems to be a problem on the first login on every char. The setting is saved, but the bars will only appear after an additional /reload. 

I'm on it!

**Comment by Goldpaw** [comment]
I believe I fixed this quite some time ago, just forgot to close the issue!
